# OverView

In this series of tutorials, we will introduce some basics of Pytorch. Pay attention that the API's of any library will be subject to changes, therefore it is very important the offcial documentation before proceeding.

we will cover the following materials in the tutorial.

1. Create tensors
2. some common mainpulations(including boardcast and einsum)

In [3]:
import torch
my_tensor = torch.tensor([[0.0, 1.0], [0.1, 0.2]])
my_tensor

tensor([[0.0000, 1.0000],
        [0.1000, 0.2000]])

In [4]:
new_tensor = my_tensor.int().float()
new_tensor

tensor([[0., 1.],
        [0., 0.]])

In [10]:
import numpy as np
np_tensor = np.array([[1.0, 2.0], [0.1, 0.2]])
tensor_from_np = torch.tensor(np_tensor)
print(tensor_from_np)
tensor_from_np = torch.tensor(np_tensor).float()
print(tensor_from_np)
to_numpy = tensor_from_np.numpy()
print(to_numpy)

tensor([[1.0000, 2.0000],
        [0.1000, 0.2000]], dtype=torch.float64)
tensor([[1.0000, 2.0000],
        [0.1000, 0.2000]])
[[1.  2. ]
 [0.1 0.2]]


In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
my_tensor.to(device=device) # https://pytorch.org/docs/stable/cuda.html

tensor([[0.0000, 1.0000],
        [0.1000, 0.2000]], device='cuda:0')